# --- !Ups

CREATE TABLE "CAT" (
    "NAME" VARCHAR NOT NULL PRIMARY KEY,
    "COLOR" VARCHAR NOT NULL
);

CREATE TABLE "LOGIN" (
    "EMAIL" VARCHAR NOT NULL PRIMARY KEY,
    "PASSWORD" VARCHAR NOT NULL
);

# --- !Downs

DROP TABLE "CAT";
DROP TABLE "LOGIN"